services:
  db:
    image: postgres:16-alpine
    container_name: restaurant_saas_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: restaurant_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  warehouse_db:
    image: postgres:16-alpine
    container_name: armazem_mora_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: armazem_mora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - warehouse_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  warehouse_postgres_data:
