-- Delivery feature (Prioridade 8, docs/DELIVERY.md), task 25.1: address + core delivery record.
-- One row per delivery tab (1:1 via tab_id), same RLS shape as card_charges (V61) - restaurant_id
-- stored directly rather than only reachable via tab_id, so the policy stays a simple column check.
-- A Tab with a delivery_details row is how "this is a delivery order" is known - same idea as
-- Balcão already being "a tab with no tables", no type/enum column added to tabs itself.
-- Status (task 27) and courier assignment (task 28) are added by later migrations, not here -
-- this table starts as just what task 25 (address capture) needs.
CREATE TABLE delivery_details (
    id UUID PRIMARY KEY,
    restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    tab_id UUID NOT NULL UNIQUE REFERENCES tabs(id) ON DELETE CASCADE,
    customer_name VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(20) NOT NULL,
    street VARCHAR(255) NOT NULL,
    number VARCHAR(20) NOT NULL,
    complement VARCHAR(255),
    neighborhood VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    zip_code VARCHAR(10),
    reference_point VARCHAR(255),
    -- Computed server-side from delivery_zones (task 26), frozen once set - never trust a
    -- client-submitted fee, see docs/DELIVERY.md security section. Defaults to 0 here because
    -- task 26 (the zone lookup that actually prices it) doesn't exist yet.
    delivery_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
    -- Unguessable link for the customer to check delivery status without an account (task 27),
    -- same pattern as reservations.access_token (V49) - generated by the app as a random UUID,
    -- never sequential, no DEFAULT here.
    access_token VARCHAR(36) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE delivery_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_details FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON delivery_details
    USING (restaurant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (restaurant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
