ALTER TABLE orders ADD COLUMN printed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE tabs ADD COLUMN receipt_printed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE restaurants ADD COLUMN auto_print_kitchen_tickets BOOLEAN NOT NULL DEFAULT FALSE;
